# Default values for ecosystem-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  imagePullSecrets:
    - name: ces-container-registries
skipPreconditionValidation: true
loadbalancer-annotations: {}
k8s-component-operator:
  enabled: true
  manager:
    image:
      registry: docker.io
      repository: cloudogu/k8s-component-operator
      tag: 1.12.2
    env:
      logLevel: info
    resourceLimits:
      memory: 105M
    resourceRequests:
      cpu: 15m
      memory: 105M
    networkPolicies:
      enabled: true
components:
  k8s-dogu-operator-crd:
    version: 2.13.0
  k8s-dogu-operator:
    version: 3.21.0
  k8s-service-discovery:
    version: 6.0.1
  k8s-blueprint-operator-crd:
    version: 3.2.0
  k8s-blueprint-operator:
    version: 3.2.0
  k8s-ces-gateway:
    version: 3.0.3
  k8s-ces-assets:
    version: 2.0.2
  k8s-ces-control:
    version: 1.10.3
  k8s-debug-mode-operator-crd:
    version: 1.0.0
  k8s-debug-mode-operator:
    version: 1.0.2
backup:
  enabled: true
  # The backup stack requires the snapshot api and snapshot controller to be installed. It is not party of the ecosystem and should be seen as an infrastructure component like the storage provisioner.
  # In cloud environments like GKE, the snapshot controller is installed by default. In other environments, it needs to be installed manually.
  # For manual installation (like in k3s environments) see https://github.com/kubernetes-csi/external-snapshotter.
  components:
    k8s-backup-operator-crd:
      version: 1.8.0
    k8s-backup-operator:
      version: 3.0.3
    k8s-velero:
      version: 11.4.0-2
monitoring:
  enabled: true
  components:
    k8s-prometheus:
      version: 75.3.5-5
    k8s-minio:
      version: 2025.6.13-3
    k8s-loki:
      version: 3.5.10-1
    k8s-promtail:
      version: 2.9.17-1
    k8s-alloy:
      version: 1.1.2-3
    k8s-support-archive-operator-crd:
      version: 1.0.0
    k8s-support-archive-operator:
      version: 1.1.1
cleanup:
  timeoutSeconds: 900
  image:
    registry: docker.io
    repository: alpine/kubectl
    tag: 1.35.2
defaultConfig:
  image:
    registry: docker.io
    repository: cloudogu/ecosystem-core-default-config
    tag: 4.1.0
  imagePullPolicy: IfNotPresent
  env:
    logLevel: info
    waitTimeoutMinutes: 5
    # If set to true, the fqdn applier will be enabled.
    # This is used in environments where dns isn't available and the loadbalancer ip should be the fqdn of the ecosystem. (Typically development environments)
    # While deploying the components, the applier will wait for the loadbalancer service to be created and use the external ip to set it in the global config as fqdn.
    # If set to false, the fqdn has to be set by the blueprint config or manually. This is required for dogus to start.
    enableFqdnApplier: false
    initialDomain: ""
