// Code generated by mockery v2.53.3. DO NOT EDIT.

package config

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockDoguConfigWriter is an autogenerated mock type for the doguConfigWriter type
type mockDoguConfigWriter struct {
	mock.Mock
}

type mockDoguConfigWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguConfigWriter) EXPECT() *mockDoguConfigWriter_Expecter {
	return &mockDoguConfigWriter_Expecter{mock: &_m.Mock}
}

// applyDefaultDoguConfig provides a mock function with given fields: ctx, defaultDoguConfig, sensitiveDefaultDoguConfig
func (_m *mockDoguConfigWriter) applyDefaultDoguConfig(ctx context.Context, defaultDoguConfig map[string]map[string]string, sensitiveDefaultDoguConfig map[string]map[string]string) error {
	ret := _m.Called(ctx, defaultDoguConfig, sensitiveDefaultDoguConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyDefaultDoguConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]map[string]string, map[string]map[string]string) error); ok {
		r0 = rf(ctx, defaultDoguConfig, sensitiveDefaultDoguConfig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguConfigWriter_applyDefaultDoguConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyDefaultDoguConfig'
type mockDoguConfigWriter_applyDefaultDoguConfig_Call struct {
	*mock.Call
}

// applyDefaultDoguConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - defaultDoguConfig map[string]map[string]string
//   - sensitiveDefaultDoguConfig map[string]map[string]string
func (_e *mockDoguConfigWriter_Expecter) applyDefaultDoguConfig(ctx interface{}, defaultDoguConfig interface{}, sensitiveDefaultDoguConfig interface{}) *mockDoguConfigWriter_applyDefaultDoguConfig_Call {
	return &mockDoguConfigWriter_applyDefaultDoguConfig_Call{Call: _e.mock.On("applyDefaultDoguConfig", ctx, defaultDoguConfig, sensitiveDefaultDoguConfig)}
}

func (_c *mockDoguConfigWriter_applyDefaultDoguConfig_Call) Run(run func(ctx context.Context, defaultDoguConfig map[string]map[string]string, sensitiveDefaultDoguConfig map[string]map[string]string)) *mockDoguConfigWriter_applyDefaultDoguConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]map[string]string), args[2].(map[string]map[string]string))
	})
	return _c
}

func (_c *mockDoguConfigWriter_applyDefaultDoguConfig_Call) Return(_a0 error) *mockDoguConfigWriter_applyDefaultDoguConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguConfigWriter_applyDefaultDoguConfig_Call) RunAndReturn(run func(context.Context, map[string]map[string]string, map[string]map[string]string) error) *mockDoguConfigWriter_applyDefaultDoguConfig_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguConfigWriter creates a new instance of mockDoguConfigWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguConfigWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguConfigWriter {
	mock := &mockDoguConfigWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
