// Code generated by mockery v2.53.3. DO NOT EDIT.

package config

import mock "github.com/stretchr/testify/mock"

// mockPasswordGenerator is an autogenerated mock type for the passwordGenerator type
type mockPasswordGenerator struct {
	mock.Mock
}

type mockPasswordGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPasswordGenerator) EXPECT() *mockPasswordGenerator_Expecter {
	return &mockPasswordGenerator_Expecter{mock: &_m.Mock}
}

// generatePassword provides a mock function with given fields: length
func (_m *mockPasswordGenerator) generatePassword(length int) string {
	ret := _m.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for generatePassword")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(length)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// mockPasswordGenerator_generatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'generatePassword'
type mockPasswordGenerator_generatePassword_Call struct {
	*mock.Call
}

// generatePassword is a helper method to define mock.On call
//   - length int
func (_e *mockPasswordGenerator_Expecter) generatePassword(length interface{}) *mockPasswordGenerator_generatePassword_Call {
	return &mockPasswordGenerator_generatePassword_Call{Call: _e.mock.On("generatePassword", length)}
}

func (_c *mockPasswordGenerator_generatePassword_Call) Run(run func(length int)) *mockPasswordGenerator_generatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *mockPasswordGenerator_generatePassword_Call) Return(_a0 string) *mockPasswordGenerator_generatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockPasswordGenerator_generatePassword_Call) RunAndReturn(run func(int) string) *mockPasswordGenerator_generatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPasswordGenerator creates a new instance of mockPasswordGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPasswordGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPasswordGenerator {
	mock := &mockPasswordGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
