// Code generated by mockery v2.53.3. DO NOT EDIT.

package config

import (
	context "context"

	dogu "github.com/cloudogu/ces-commons-lib/dogu"
	k8s_registry_libconfig "github.com/cloudogu/k8s-registry-lib/config"

	mock "github.com/stretchr/testify/mock"
)

// mockDoguConfigRepo is an autogenerated mock type for the doguConfigRepo type
type mockDoguConfigRepo struct {
	mock.Mock
}

type mockDoguConfigRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguConfigRepo) EXPECT() *mockDoguConfigRepo_Expecter {
	return &mockDoguConfigRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, doguConfig
func (_m *mockDoguConfigRepo) Create(ctx context.Context, doguConfig k8s_registry_libconfig.DoguConfig) (k8s_registry_libconfig.DoguConfig, error) {
	ret := _m.Called(ctx, doguConfig)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 k8s_registry_libconfig.DoguConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, k8s_registry_libconfig.DoguConfig) (k8s_registry_libconfig.DoguConfig, error)); ok {
		return rf(ctx, doguConfig)
	}
	if rf, ok := ret.Get(0).(func(context.Context, k8s_registry_libconfig.DoguConfig) k8s_registry_libconfig.DoguConfig); ok {
		r0 = rf(ctx, doguConfig)
	} else {
		r0 = ret.Get(0).(k8s_registry_libconfig.DoguConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, k8s_registry_libconfig.DoguConfig) error); ok {
		r1 = rf(ctx, doguConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguConfigRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockDoguConfigRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - doguConfig k8s_registry_libconfig.DoguConfig
func (_e *mockDoguConfigRepo_Expecter) Create(ctx interface{}, doguConfig interface{}) *mockDoguConfigRepo_Create_Call {
	return &mockDoguConfigRepo_Create_Call{Call: _e.mock.On("Create", ctx, doguConfig)}
}

func (_c *mockDoguConfigRepo_Create_Call) Run(run func(ctx context.Context, doguConfig k8s_registry_libconfig.DoguConfig)) *mockDoguConfigRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(k8s_registry_libconfig.DoguConfig))
	})
	return _c
}

func (_c *mockDoguConfigRepo_Create_Call) Return(_a0 k8s_registry_libconfig.DoguConfig, _a1 error) *mockDoguConfigRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguConfigRepo_Create_Call) RunAndReturn(run func(context.Context, k8s_registry_libconfig.DoguConfig) (k8s_registry_libconfig.DoguConfig, error)) *mockDoguConfigRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name
func (_m *mockDoguConfigRepo) Get(ctx context.Context, name dogu.SimpleName) (k8s_registry_libconfig.DoguConfig, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 k8s_registry_libconfig.DoguConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dogu.SimpleName) (k8s_registry_libconfig.DoguConfig, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dogu.SimpleName) k8s_registry_libconfig.DoguConfig); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(k8s_registry_libconfig.DoguConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dogu.SimpleName) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguConfigRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockDoguConfigRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name dogu.SimpleName
func (_e *mockDoguConfigRepo_Expecter) Get(ctx interface{}, name interface{}) *mockDoguConfigRepo_Get_Call {
	return &mockDoguConfigRepo_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *mockDoguConfigRepo_Get_Call) Run(run func(ctx context.Context, name dogu.SimpleName)) *mockDoguConfigRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dogu.SimpleName))
	})
	return _c
}

func (_c *mockDoguConfigRepo_Get_Call) Return(_a0 k8s_registry_libconfig.DoguConfig, _a1 error) *mockDoguConfigRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguConfigRepo_Get_Call) RunAndReturn(run func(context.Context, dogu.SimpleName) (k8s_registry_libconfig.DoguConfig, error)) *mockDoguConfigRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrMerge provides a mock function with given fields: ctx, doguConfig
func (_m *mockDoguConfigRepo) SaveOrMerge(ctx context.Context, doguConfig k8s_registry_libconfig.DoguConfig) (k8s_registry_libconfig.DoguConfig, error) {
	ret := _m.Called(ctx, doguConfig)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrMerge")
	}

	var r0 k8s_registry_libconfig.DoguConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, k8s_registry_libconfig.DoguConfig) (k8s_registry_libconfig.DoguConfig, error)); ok {
		return rf(ctx, doguConfig)
	}
	if rf, ok := ret.Get(0).(func(context.Context, k8s_registry_libconfig.DoguConfig) k8s_registry_libconfig.DoguConfig); ok {
		r0 = rf(ctx, doguConfig)
	} else {
		r0 = ret.Get(0).(k8s_registry_libconfig.DoguConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, k8s_registry_libconfig.DoguConfig) error); ok {
		r1 = rf(ctx, doguConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguConfigRepo_SaveOrMerge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrMerge'
type mockDoguConfigRepo_SaveOrMerge_Call struct {
	*mock.Call
}

// SaveOrMerge is a helper method to define mock.On call
//   - ctx context.Context
//   - doguConfig k8s_registry_libconfig.DoguConfig
func (_e *mockDoguConfigRepo_Expecter) SaveOrMerge(ctx interface{}, doguConfig interface{}) *mockDoguConfigRepo_SaveOrMerge_Call {
	return &mockDoguConfigRepo_SaveOrMerge_Call{Call: _e.mock.On("SaveOrMerge", ctx, doguConfig)}
}

func (_c *mockDoguConfigRepo_SaveOrMerge_Call) Run(run func(ctx context.Context, doguConfig k8s_registry_libconfig.DoguConfig)) *mockDoguConfigRepo_SaveOrMerge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(k8s_registry_libconfig.DoguConfig))
	})
	return _c
}

func (_c *mockDoguConfigRepo_SaveOrMerge_Call) Return(_a0 k8s_registry_libconfig.DoguConfig, _a1 error) *mockDoguConfigRepo_SaveOrMerge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguConfigRepo_SaveOrMerge_Call) RunAndReturn(run func(context.Context, k8s_registry_libconfig.DoguConfig) (k8s_registry_libconfig.DoguConfig, error)) *mockDoguConfigRepo_SaveOrMerge_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguConfigRepo creates a new instance of mockDoguConfigRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguConfigRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguConfigRepo {
	mock := &mockDoguConfigRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
