// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockConfigApplier is an autogenerated mock type for the configApplier type
type mockConfigApplier struct {
	mock.Mock
}

type mockConfigApplier_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConfigApplier) EXPECT() *mockConfigApplier_Expecter {
	return &mockConfigApplier_Expecter{mock: &_m.Mock}
}

// ApplyDefaultConfig provides a mock function with given fields: ctx
func (_m *mockConfigApplier) ApplyDefaultConfig(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ApplyDefaultConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockConfigApplier_ApplyDefaultConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyDefaultConfig'
type mockConfigApplier_ApplyDefaultConfig_Call struct {
	*mock.Call
}

// ApplyDefaultConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockConfigApplier_Expecter) ApplyDefaultConfig(ctx interface{}) *mockConfigApplier_ApplyDefaultConfig_Call {
	return &mockConfigApplier_ApplyDefaultConfig_Call{Call: _e.mock.On("ApplyDefaultConfig", ctx)}
}

func (_c *mockConfigApplier_ApplyDefaultConfig_Call) Run(run func(ctx context.Context)) *mockConfigApplier_ApplyDefaultConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockConfigApplier_ApplyDefaultConfig_Call) Return(_a0 error) *mockConfigApplier_ApplyDefaultConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockConfigApplier_ApplyDefaultConfig_Call) RunAndReturn(run func(context.Context) error) *mockConfigApplier_ApplyDefaultConfig_Call {
	_c.Call.Return(run)
	return _c
}

// newMockConfigApplier creates a new instance of mockConfigApplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConfigApplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConfigApplier {
	mock := &mockConfigApplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
