{{- if not (.Capabilities.APIVersions.Has "k8s.cloudogu.com/v1/Component") -}}
  {{- fail "CRD k8s.cloudogu.com/v1/Component is not installed." -}}
{{- end -}}


{{ if not (.Values.skipPreconditionValidation | default false) }}
  {{ include "ecosystem-core.requireSecretOrConfigMap" (dict "namespace" .Release.Namespace "resourceType" "Secret" "name" "component-operator-helm-registry" "keys" (list "config.json")) }}
  {{ include "ecosystem-core.requireSecretOrConfigMap" (dict "namespace" .Release.Namespace "resourceType" "Secret" "name" "ces-container-registries" "keys" (list ".dockerconfigjson")) }}
  {{ include "ecosystem-core.requireSecretOrConfigMap" (dict "namespace" .Release.Namespace "resourceType" "Secret" "name" "k8s-dogu-operator-dogu-registry" "keys" (list "endpoint" "username" "password")) }}

  {{ include "ecosystem-core.requireSecretOrConfigMap" (dict "namespace" .Release.Namespace "resourceType" "ConfigMap" "name" "component-operator-helm-repository" "keys" (list "endpoint" "plainHttp" "schema")) }}
{{ end }}